MD_VERSION_MAJOR = 0
MD_VERSION_MINOR = 5
MD_VERSION_RELEASE = 2
MD_VERSION = $(MD_VERSION_MAJOR).$(MD_VERSION_MINOR).$(MD_VERSION_RELEASE)
VERSION_DEFS = -DMD_VERSION="\"$(MD_VERSION)\"" \
			   -DMD_VERSION_MINOR="\"$(MD_VERSION_MINOR)\"" \
			   -DMD_VERSION_MAJOR="\"$(MD_VERSION_MAJOR)\""	\
			   -DMD_VERSION_RELEASE="\"$(MD_VERSION_RELEASE)\""

PREFIX = /usr
MANPREFIX = $(PREFIX)/share/man

MD4C_SRC = src/md4c.c
MD4LIBS = src/md4c.o src/md4c-html.o src/entity.o

CC = c99
CFLAGS = -O2 -pipe
LIBCFLAGS = $(CFLAGS)
